paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
plugins: 
- jekyll-paginate
- jekyll-feed

exclude: ["README.md"] # files to exclude

markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  coderay_tab_width: 2
  syntax_highlighter: coderay

destination: public
highlighter: rouge
safe: false

title: Tao Lele
description: Stylish Jekyll Theme
disqus: blog-v2tvzqcwyy # add disqus short name here

author:
  name: Tao Lele
  email: kiss5jenny@gmail.com
  github: shunmian
  twitter: 
  bio: Fashion is Identity
  email_md5: 59424d7b03e8a932aa65d991294d8ab0

feed:
  path: feed.xml
categories_path: categories.html
tags_path: tags.html

baseurl: http://www.shunmian.me
